// src/app/api/bank/ta/export/route.ts
// Bank: export TA programmes as CSV

export const dynamic = 'force-dynamic'

import { NextRequest, NextResponse } from 'next/server'
import { auth } from '@clerk/nextjs/server'
import { connectDB } from '@/lib/db'
import { User, TAProgramme, Business } from '@/models'

function esc(v: unknown): string {
  const s = String(v ?? '')
  return s.includes(',') || s.includes('"') || s.includes('\n')
    ? `"${s.replace(/"/g, '""')}"`
    : s
}

export async function GET(req: NextRequest) {
  const { userId } = await auth()
  if (!userId) return NextResponse.json({ error: 'Unauthorised' }, { status: 401 })

  await connectDB()

  const user = await User.findOne({ clerkId: userId }).lean() as any
  if (!user || !['bank_admin', 'bank_staff', 'platform_admin'].includes(user.role)) {
    return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
  }

  const programmes = await TAProgramme.find({ tenantId: user.tenantId })
    .sort({ createdAt: -1 })
    .lean() as any[]

  const bizIds = Array.from(new Set(programmes.map(p => String(p.businessId))))
  const businesses = await Business.find({ _id: { $in: bizIds } }).lean() as any[]
  const bizMap: Record<string, any> = {}
  for (const b of businesses) bizMap[String(b._id)] = b

  const headers = [
    'business_name', 'business_email', 'capacity_level', 'area',
    'parameter_id', 'recommendation', 'tools', 'timeframe_weeks',
    'priority', 'status', 'progress_pct', 'start_date', 'completed_date',
    'auto_generated', 'created_at',
  ]

  const rows = programmes.map(p => {
    const biz = bizMap[String(p.businessId)] ?? {}
    return [
      esc(biz.name),
      esc(biz.email),
      esc(p.capacityLevel),
      esc(p.area),
      esc(p.parameterId),
      esc(p.recommendation),
      esc((p.tools ?? []).join('; ')),
      esc(p.timeframeWeeks),
      esc(p.priority),
      esc(p.status),
      esc(p.progressPercent ?? 0),
      esc(p.startDate ? new Date(p.startDate).toISOString().slice(0, 10) : ''),
      esc(p.completedDate ? new Date(p.completedDate).toISOString().slice(0, 10) : ''),
      esc(p.autoGenerated ? 'yes' : 'no'),
      esc(new Date(p.createdAt).toISOString().slice(0, 10)),
    ].join(',')
  })

  const csv = [headers.join(','), ...rows].join('\n')
  const date = new Date().toISOString().slice(0, 10)

  return new NextResponse(csv, {
    headers: {
      'Content-Type': 'text/csv',
      'Content-Disposition': `attachment; filename="ta-programmes-${date}.csv"`,
    },
  })
}
